---
aws_access: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
aws_secret: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
aws_access_key: "{{aws_access}}"
aws_secret_key: "{{aws_secret}}"

region: "ap-southeast-2"
sg_name: "test-sg" # Name for new AWS Security Group
vpc_id: "vpc-XXXXXXXX" # Existing VPCID from lab account
